function TorsionValuation(K, l, x)
    if K eq Rationals() then
        return Valuation(x, l);
    else
        L := [];
        // Handle zero element: valuation is infinity
        if x eq 0 then
            return Infinity();
        end if;
        // Get the ring of integers of K
        OK := Integers(K);
        // Factor the ideal generated by l
        fac := Factorization(ideal<OK | l>);
        // Ensure there is at least one prime above l
        if #fac eq 0 then
            error "No prime ideals found above", l;
        end if;
        // Select the nth prime ideal above l
        for n := 1 to #fac do
            lambda := fac[n][1];
            val:=Valuation(x, lambda);
            f:=InertiaDegree(lambda);
            L:=Append(L,f*val);
        end for;
        m, pos := Max(L);
        return m;
    end if;
end function;

function polynomial_from_list(L)
    R<x>:=PolynomialRing(Rationals());
    P:=R!0;
    for i := 1 to #L do
        P +:= L[i]*x^(i-1);
    end for;
    return P;
end function;

function unpack_aps(fld, pb, num, den, cyc, aps, genus)
//unpack_aps(K, hecke_ring_power_basis[i], hecke_ring_numerators[i], hecke_ring_denominators[i], hecke_ring_cyclotomic_generator[i], aps[i], genus);
a := fld.1;
//first compute the basis
basis := [];
if pb eq 1 then
    for k := 0 to genus-1 do
        basis := Append(basis, a^k);
    end for;
elif cyc eq 0 then
    for j := 1 to #num do
        b := 0;
        for k := 0 to genus-1 do
            b := b + num[j][k+1]*a^k;
        end for;
        basis := Append(basis, b/den[j]);
    end for;
else m := cyc;
    Cyc := CyclotomicField(m);
    zetam := Cyc.1;
    for k := 1 to genus do
        basis := Append(basis, zetam^(k-1));
    end for;
end if;

//now we compute the aps in terms of the basis
apsi := [];
for j := 1 to #aps do
    for k := 1 to #basis do
    if cyc ne 0 then
        F := Compositum(Cyc, fld);
        apsij := F!0;
        for k := 1 to #aps do
            apsij := apsij + F!(aps[j][k]*zetam^(k-1));
        end for;
    else
        apsij := fld!0;
        for k := 1 to #basis do
            apsij := apsij + aps[j][k]*basis[k];
        end for;
    end if;
    end for;
    apsi := Append(apsi, apsij);
end for;
return apsi;
end function;




// List of the predicted torsion orders for the A_f
list_predicted := [];
// List of the torsion orders matching the bound gcd Np
list := [];
// List of the primes dividing the predicted torsion orders
list_of_primes := [];
primes := PrimesUpTo(100000); // We need a function that computes the i-th prime. If the bound is not enough, change this line.
genus := #fields[1] - 1;

for i:=1 to #labels do
    N := levels[i];
    iscm := cm[i];
    if iscm eq 0 then
        K := NumberField(polynomial_from_list(fields[i]));
        OK := Integers(K);
        L := [];
        LNp := [];
        apsi := unpack_aps(K, hecke_ring_power_basis[i], hecke_ring_numerators[i], hecke_ring_denominators[i], hecke_ring_cyclotomic_generator[i], aps[i], genus);        
        for j := 1 to #aps[i] do
            p := primes[j];
            ap := apsi[j];
            if p-1 le genus then
                Facp := Factorization(p*OK);
                ram := [e[2] : e in Facp];
                ep := Max(ram); // Absolute ramification index
                // Check if torsion injects into the reduction
            else ep := 1;
            end if;
            if ep lt p-1 then
                if N mod p ne 0 and ap ne 0 then
                    // Compute P_p^\lambda(1) and the corresponding valuation at l of the torsion order
                    bp := 1;
                    chip := ap/ComplexConjugate(ap);
                    x := chip*p+1-ap;
                    X := Integers()!Norm(x);
                    fac := Factorization(X);
                    for k := 1 to #fac do
                        l := fac[k][1];
                        fn := TorsionValuation(K, l, x);
                        bp := bp * l ^ fn;
                    end for;
                    // chip := chi(p);
                    // Fchi := Parent(chip);
                    // F := Compositum(Fchi, K);
                    // x := F!chip*p+1-ap;
                    L := Append(L, bp);
                    LNp := Append(LNp, X);
                end if;
            end if;
        end for;
        // Take the gcd over all primes
        g := GCD(L);
        // Take the gcd of the rational points over the reductions for the same primes       
        gp := GCD(LNp);
        if g eq gp then
        // If they are equal, then the precited order is equal to the bound. We add it to all the lists.
            if g notin list then 
                list := Append(list, g); 
            end if;
            if g notin list_predicted then
                list_predicted := Append(list_predicted, g); 
                F := Factorization(g);
                for k := 1 to #F do
                if F[k][1] notin list_of_primes then
                list_of_primes := Append(list_of_primes, F[k][1]);
                end if;
                end for;
            end if;
            print "f =", labels[i];
            print "predicted torsion order equal to bound =", g;
        else
        // If they are not equal, we only add it to the list of the predicted torsion orders.
            if g notin list_predicted then
                list_predicted := Append(list_predicted, g); 
                F := Factorization(g);
                for k := 1 to #F do
                if F[k][1] notin list_of_primes then
                list_of_primes := Append(list_of_primes, F[k][1]);
                end if;
                end for;
            end if;
            print "f =", labels[i];
            print "predicted torsion order =", g; //this number divides the torsion order of an abelian variety isogenous to A_f. It is equal if the primes dividing g have a unique prime above them in K.
        end if;
    end if;
end for;
list_predicted;
list;
list_of_primes;
